dist: trusty

language: node_js

node_js:
  - "0.10.46"
  - "4"
  - "6"

env:
  global:
    - COVERALLS_REPO_TOKEN=nQmloGTal0SeXbiRqNBvqtDUnDFfaA9Cx
    - COVERALLS_PARALLEL=true

cache:
  directories:
    - node_modules

script:
  - npm test

after_script:
  - npm run coveralls

notifications:
  webhooks: https://coveralls.io/webhook?repo_token=COVERALLS_REPO_TOKEN
