sudo: required
dist: trusty

os:
  - linux

language: node_js

node_js:
  - "0.10"
  - "4"
  - "6"
  - "8"
  - "10"
  - "12"

cache:
  directories:
    - node_modules

script:
  - npm test

after_script:
  - npm run coveralls

notifications:
  webhooks: https://coveralls.io/webhook?repo_token=COVERALLS_REPO_TOKEN
